# -*- coding: utf-8 -*-
"""Prg1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JjvooZK7kNR4bA2hHhWBmCyNSQxEgYGA

Enunciado: Leer dos numeros enteros y calcular e imprimir la suma y el producto
Desarrollado por: 2023-1_FP_1_Dia
Fecha: 09/03/2023

# Version: 1.0
"""

#LECTURA DE DATOS
print("PROGRAMA QUE CAPTURA POR TECLADO DOS NUMEROS, LOS SUMA Y MULTIPLICA")
print("Ingrese el Primer Numero: ")
v_numUno=input() #Lectura
v_numUno=int(v_numUno) #Conversion de tipo de dato
print("Ingrese el Segundo Numero: ")
v_numDos=input() #Lectura
v_numDos=int(v_numDos) #Conversion de tipo de dato

#PROCESOS
v_sumNum = v_numUno + v_numDos #Suma de numeros
v_proNum = v_numUno * v_numDos #Producto de los numeros

#SALIDAS
print("La suma de los nuneros es: ")
print(v_sumNum)
print("El producto de los nuneros es: ")
print(v_proNum)